# 带[ ]括号的，就是多选，不带的就是单选
boss:
  sayHi: "您好，我对这个岗位以及贵公司都很有兴趣，也觉得岗位非常适合自己，相信自己也能为贵公司提供价值。可以查看我的简历，如果您觉得合适，可以随时联系我，感谢" #必须要关闭boss的自动打招呼
  keywords: ["Java" ] # 需要搜索的职位,会依次投递
  industry: [ "不限" ] # 公司行业，只能选三个，相关代码枚举的部分，如果需要其他的需要自己找
  cityCode: "杭州" # 只列举了部分,如果没有的需要自己找：目前支持的：全国 北京 上海 广州 深圳 成都
  areaCode:  [ "滨江区", "西湖区","拱墅区","萧山区","上城区","余杭区"] # 只列举了部分,如果没有的需要自己找
  experience: [ "3-5年" ] # 工作经验："应届毕业生", "1年以下", "1-3年", "3-5年", "5-10年", "10年以上"
  jobType: "全职" #求职类型："全职", "兼职"
  salary: "10-20K" # 薪资（单选）："3K以下", "3-5K", "5-10K", "10-20K", "20-50K", "50K以上"
  degree: ["大专", "本科" ] # 学历: "初中及以下", "中专/中技", "高中", "大专", "本科", "硕士", "博士"
  scale: [ "20-99人","100-499人","500-999人" ] # 公司规模："0-20人", "20-99人", "100-499人", "500-999人", "1000-9999人", "10000人以上"
  stage: [ "不限" ] # "未融资", "天使轮", "A轮", "B轮", "C轮", "D轮及以上", "已上市", "不需要融资"

job51:
  jobArea: ["杭州"]  #工作地区：目前只有【北京 成都 上海 广州 深圳】
  keywords: ["中级Java"] #关键词：依次投递
  salary: ["1.5-2万"] #薪资范围：只能选5个【"2千以下", "2-3千", "3-4.5千", "4.5-6千", "6-8千", "0.8-1万", "1-1.5万", "1.5-2万", "2-3万", "3-4万", "4-5万", "5万以上"】

lagou:
  keywords: ["Java"] #搜索关键词
  cityCode: "杭州" #拉勾城市名没有限制,直接填写即可
  salary: "15k-25k" #薪资【"不限","2k以下", "2k-5k", "5k-10k", "10k-15k", "15k-25k", "25k-50k", "50k以上"】
  scale: ["不限"] #公司规模【"不限","少于15人", "15-50人", "50-150人", "150-500人", "500-2000人", "2000人以上"】

liepin:
  cityCode: "杭州" # 目前支持的：全国 北京 上海 广州 深圳 成都
  keywords: ["Java"]
  salary: "不限" # 填 15$30 代表 15k-30k

zhilian:
  cityCode: "杭州"
  salary: "15000,20000" #薪资区间
  keywords: ["java开发工程师"]